language: python
python:
  - "3.5"
  - "3.5-dev" # 3.5 development branch

# command to install dependencies
install:
  - pip install -r requirements.txt
  - ./setup.py install

# command to run tests
script: "./setup.py test && ./setup.py behave_test --tags=mandatory"
